title: "NETworkManager"
description: "A powerful tool for managing networks and troubleshoot network problems!"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
aux_links:
  '<button id="theme-toggle"></button>':
    - '#"onclick="modeSwitcher()"'
search_enabled: true
plugins:
  - jemoji
